"""add user name email fields

Revision ID: 10539a95763c
Revises: 72d201910758
Create Date: 2026-07-08 13:56:08.404419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10539a95763c'
down_revision: Union[str, None] = '72d201910758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default fuer bestehende Zeilen (z.B. Seed-Admin), danach entfernt,
    # damit die App-seitigen Defaults gelten.
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False, server_default=''))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False, server_default=''))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False, server_default=''))
    op.alter_column('users', 'first_name', server_default=None)
    op.alter_column('users', 'last_name', server_default=None)
    op.alter_column('users', 'email', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
