"""add bed_capacity to admin_config

Revision ID: 3bf6e6751de0
Revises: 10539a95763c
Create Date: 2026-07-08 14:03:22.302135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf6e6751de0'
down_revision: Union[str, None] = '10539a95763c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_config', sa.Column('bed_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_config', 'bed_capacity')
    # ### end Alembic commands ###
