"""add admin_config table

Revision ID: 4b1f58a2954f
Revises: 837507e6e999
Create Date: 2026-07-06 18:44:38.644848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1f58a2954f'
down_revision: Union[str, None] = '837507e6e999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bexio_client_id', sa.String(), nullable=True),
    sa.Column('bexio_client_secret', sa.String(), nullable=True),
    sa.Column('allocation_mode', sa.String(), nullable=True),
    sa.Column('monthly_budget_chf', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_planning_year', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_config')
    # ### end Alembic commands ###
