"""add bexio_api_token to admin_config

Revision ID: 671cd1b79417
Revises: 4b1f58a2954f
Create Date: 2026-07-06 19:01:00.458041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671cd1b79417'
down_revision: Union[str, None] = '4b1f58a2954f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_config', sa.Column('bexio_api_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_config', 'bexio_api_token')
    # ### end Alembic commands ###
