"""initial schema

Revision ID: 837507e6e999
Revises: 
Create Date: 2026-07-06 14:53:35.381409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837507e6e999'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_nr', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('position_bexio_id', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', 'document_id', 'position_bexio_id', name='uq_line_item')
    )
    op.create_table('oauth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_nr', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('credit_note_date', sa.Date(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_invoice_bexio_id', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_notes_document_nr'), 'credit_notes', ['document_nr'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_nr', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_order_bexio_id', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_document_nr'), 'invoices', ['document_nr'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_nr', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_quote_bexio_id', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_document_nr'), 'orders', ['document_nr'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_nr', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kb_item_status_id', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_document_nr'), 'quotes', ['document_nr'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_key', sa.String(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('credit_note_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('kunde', sa.String(), nullable=False),
    sa.Column('anlass', sa.String(), nullable=False),
    sa.Column('linked_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('service_start', sa.Date(), nullable=True),
    sa.Column('service_end', sa.Date(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('pax_soll', sa.Integer(), nullable=True),
    sa.Column('pax_ist', sa.Integer(), nullable=True),
    sa.Column('nights_soll', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nights_ist', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('umsatz_soll', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('umsatz_ist', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_key'), 'bookings', ['booking_key'], unique=True)
    op.create_table('monthly_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('nights_soll', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nights_ist', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('days', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pax_nights_soll', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pax_nights_ist', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('umsatz_soll', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('umsatz_ist', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'year', 'month', name='uq_monthly_allocation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_allocations')
    op.drop_index(op.f('ix_bookings_booking_key'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_quotes_document_nr'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_orders_document_nr'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_invoices_document_nr'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_credit_notes_document_nr'), table_name='credit_notes')
    op.drop_table('credit_notes')
    op.drop_table('oauth_token')
    op.drop_table('line_items')
    op.drop_table('contacts')
    # ### end Alembic commands ###
